### ISSUE TITLE
[bug] NCCL WARN NET/OFI Only EFA provider is supported

### ISSUE THREAD

**Issue by mkserge** [aws/deep-learning-containers#2675]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [ ] (If applicable) I've attached the script to reproduce the bug
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*

I am trying to run PyTorch DDP with NCCL backend on SageMaker. I have my own Docker image which uses the following as a base
`763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.13.1-gpu-py38-cu117-ubuntu20.04-sagemaker`. The Docker image does minimal changes to the base image, just copying some code and setting some environment variables like `SAGEMAKER_PROGRAM` etc.

This is configured as a SageMaker Training job through the AWS Console (I am working on someone else's setup, so no full control of the underlying details).

Running the SageMaker training job, I see the following warnings in the logs. and then the job "hangs".
```
algo-1:249:249 [0] ofi_init:1288 NCCL WARN NET/OFI Only EFA provider is supported
algo-1:249:249 [0] ofi_init:1339 NCCL WARN NET/OFI aws-ofi-nccl initialization failed
```
The instance is `ml.p3.16xlarge` with 8 V100 GPUs. I don't need inter-node communication, just intra-node communication between the GPUs. I also have no issues running my code on EC2 instance (`ml.p3.16xlarge`, but not using the docker image directly)

It looks like the base image is configured to have NCCL with only EFA support. Is that correct? EFA is supported only on `p3dn.24xlarge` and `p4d.24xlarge` instances, which is not my use-case, which I believe is what is causing the issue.

So the question is how can one use this base docker image to train PyTorch DDP with NCCL as a backend (without EFA) on an `ml.p3.16xlarge` instance)?

*DLC image/dockerfile:*

`763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.13.1-gpu-py38-cu117-ubuntu20.04-sagemaker`

*Current behavior:*

Throws 
```
algo-1:249:249 [0] ofi_init:1288 NCCL WARN NET/OFI Only EFA provider is supported
algo-1:249:249 [0] ofi_init:1339 NCCL WARN NET/OFI aws-ofi-nccl initialization failed
```
and training "hangs"

*Expected behavior:*

No EFA warnings and model trains with DDP on NCCL backend.

*Additional context:*

**Comment by ShiboXing** [comment]
Hi @mkserge, we are taking a look. Thanks for the issue

**Comment by roywei** [comment]
Interested to learn the root cause as well. EFA should not fail and cause hang on unsupported instances.
I can think of a few workarounds:
1. make sure you are using `distribution={"pytorchddp":{"enabled":True}.` for DDP + NCCL launcher in SageMaker estimator API.
2. try overriding the environment variable FI_PROVIDER in your training script to force NCCL use Sockets instead of EFA.
`FI_PROVIDER=Sockets`
In sagemaker training toolkit we are suppose to only set FI_PROVIDER to efa when the instance supports EFA https://github.com/aws/sagemaker-training-toolkit/blob/d2488c6e8b9b2e496d6b3394e46edfadc53c1b3a/src/sagemaker_training/torch_distributed.py#L72

setting it to Sockets can force disable EFA.

**Comment by mkserge** [comment]
Hi, thank you both for looking into this. I appreciate the help.

To provide an update, it looks like the "hanging" was actually a crazy slow-down of my training job. Going from DataParallel to DistributedDataParallel with PyTorch made my training go from 5 minutes to 2 hours and 30 minutes, making me believe the training was hanging. This slow-down is pretty unexpected.

I do still observe the messages I pasted above with `aws-ofi-nccl` initialization failing. Will try to override the FI_PROVIDER and will post the results here.

I also tried re-building the Docker image from scratch, removing all the EFA installation bits from the Dockerfile, but this again results in significant slow-down of the job (10x drop in speed). 

@roywei , maybe a stupid question, but I couldn't figure out how to pass `distribution={"pytorchddp":{"enabled":True}` to the SageMaker estimator API. The job I am working with is being created from AWS Console -> Amazon SageMaker ->  Training (from the left menu) -> Training Jobs -> Create Training Job.

The job that is created from the UI has `Your own algorithm container in ECR` selected with a path of the docker image in ECR. This docker image has `SAGEMAKER_PROGRAM` ENV set to the entry point of the training script. No estimators inside. Is there a way to pass `distribution={"pytorchddp":{"enabled":True}` through the UI like this? (I am also interested in this because I want to try out `smddp` backend).

Thank you again for looking into this. I can try to provide more details if needed.

**Comment by roywei** [comment]
Ok, looks like some miss config could causing the job hanging and the job is not failing which is expected. (EFA failed to initialize and NCCL fallback to Socket automatically). I've never tried create training job from Console UI, but the recommended way is through SageMaker notebook instance or using SageMaker python SDK to launch a distributed training job. You need the Pytorch Estimator class where you can configure instance type and how to want to train distributed. 
https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html

refer to this blog post for example, pytorch DDP + NCCL works the same way as PyTorch + SMDDP: https://aws.amazon.com/blogs/machine-learning/run-pytorch-lightning-and-native-pytorch-ddp-on-amazon-sagemaker-training-featuring-amazon-search/
more examples
https://github.com/aws/amazon-sagemaker-examples/tree/main/training/distributed_training/pytorch/data_parallel

**Comment by DhruvaBansal00** [comment]
Did this issue ever get resolved? I am facing similar issues:

Using the base image `763104351884.dkr.ecr.us-west-2.amazonaws.com/huggingface-pytorch-training:1.13.1-transformers4.26.0-gpu-py39-cu117-ubuntu20.04`, I am trying to train a model using Deepspeed zero stage 3 and seeing the following messages. This is on an G5 12xlarge AWS EC2 machine.:

```
16d2d618f560:123:890 [0] ofi_init:1355 NCCL WARN NET/OFI aws-ofi-nccl initialization failed
16d2d618f560:123:890 [0] NCCL INFO NET/IB : No device found.
16d2d618f560:123:890 [0] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0> [1]eth0:172.17.0.2<0>
16d2d618f560:123:890 [0] NCCL INFO Using network Socket
16d2d618f560:125:125 [2] NCCL INFO cudaDriverVersion 12000
16d2d618f560:124:891 [1] NCCL INFO NET/OFI Using aws-ofi-nccl 1.4.0aws
16d2d618f560:124:891 [1] NCCL INFO NET/OFI Setting FI_EFA_FORK_SAFE environment variable to 1
16d2d618f560:126:126 [3] NCCL INFO cudaDriverVersion 12000
16d2d618f560:125:125 [2] NCCL INFO Bootstrap : Using lo:127.0.0.1<0>
16d2d618f560:126:126 [3] NCCL INFO Bootstrap : Using lo:127.0.0.1<0>
16d2d618f560:125:125 [2] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol.
16d2d618f560:125:125 [2] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin symbol (v4 or v5).

16d2d618f560:124:891 [1] ofi_init:1304 NCCL WARN NET/OFI Only EFA provider is supported

16d2d618f560:124:891 [1] ofi_init:1355 NCCL WARN NET/OFI aws-ofi-nccl initialization failed
16d2d618f560:124:891 [1] NCCL INFO NET/IB : No device found.
16d2d618f560:124:891 [1] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0> [1]eth0:172.17.0.2<0>
16d2d618f560:124:891 [1] NCCL INFO Using network Socket
16d2d618f560:126:126 [3] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol.
16d2d618f560:126:126 [3] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin symbol (v4 or v5).
16d2d618f560:125:892 [2] NCCL INFO NET/OFI Using aws-ofi-nccl 1.4.0aws
16d2d618f560:125:892 [2] NCCL INFO NET/OFI Setting FI_EFA_FORK_SAFE environment variable to 1
16d2d618f560:126:893 [3] NCCL INFO NET/OFI Using aws-ofi-nccl 1.4.0aws
16d2d618f560:126:893 [3] NCCL INFO NET/OFI Setting FI_EFA_FORK_SAFE environment variable to 1

16d2d618f560:125:892 [2] ofi_init:1304 NCCL WARN NET/OFI Only EFA provider is supported

16d2d618f560:125:892 [2] ofi_init:1355 NCCL WARN NET/OFI aws-ofi-nccl initialization failed
16d2d618f560:125:892 [2] NCCL INFO NET/IB : No device found.
16d2d618f560:125:892 [2] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0> [1]eth0:172.17.0.2<0>
16d2d618f560:125:892 [2] NCCL INFO Using network Socket

16d2d618f560:126:893 [3] ofi_init:1304 NCCL WARN NET/OFI Only EFA provider is supported

16d2d618f560:126:893 [3] ofi_init:1355 NCCL WARN NET/OFI aws-ofi-nccl initialization failed
16d2d618f560:126:893 [3] NCCL INFO NET/IB : No device found.
16d2d618f560:126:893 [3] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0> [1]eth0:172.17.0.2<0>
16d2d618f560:126:893 [3] NCCL INFO Using network Socket
16d2d618f560:123:890 [0] NCCL INFO NCCL_P2P_LEVEL set by environment to LOC
16d2d618f560:126:893 [3] NCCL INFO NCCL_P2P_LEVEL set by environment to LOC
16d2d618f560:124:891 [1] NCCL INFO NCCL_P2P_LEVEL set by environment to LOC
16d2d618f560:125:892 [2] NCCL INFO NCCL_P2P_LEVEL set by environment to LOC
16d2d618f560:124:891 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] 2/-1/-1->1->0
16d2d618f560:123:890 [0] NCCL INFO Channel 00/02 :    0   1   2   3
16d2d618f560:126:893 [3] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] -1/-1/-1->3->2
16d2d618f560:125:892 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 3/-1/-1->2->1
16d2d618f560:123:890 [0] NCCL INFO Channel 01/02 :    0   1   2   3
16d2d618f560:123:890 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
[2023-07-08 00:23:31,415] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 123
[2023-07-08 00:23:31,416] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 124
[2023-07-08 00:23:31,669] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 125
[2023-07-08 00:23:31,761] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 126
[2023-07-08 00:23:31,761] [ERROR] [launch.py:321:sigkill_handler] ['/opt/conda/bin/python3.9', '-u', 'core/driver.py', '--local_rank=3', '--training_config', '/training_configs/default_config.json'] exits with return code = -7
```

**Comment by zippeurfou** [comment]
This issue is also affecting tensorflow estimator.
```
NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol.
NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin symbol (v4 or v5).
```

**Comment by gitrc** [comment]
New year, new updates maybe?  

I'm facing the same problem.  I worked around the EFA requirement by attaching an ENI with EFA support to the EC2 instance but then ran into the 'Failed to find ncclCol..' messages plus the original set of messages "NCCL INFO Could not enable P2P between dev 1(=1c0) and dev 2(=1d0)" and "NCCL INFO P2P is disabled between connected GPUs 3 and 2. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1."

Going to log AWS Support cases now and reference this thread.

**Comment by roywei** [comment]
Hi everyone, 

I think we've diverged from the original issue. Although the error/logs maybe similar and you may see NCCL hangs, each problem can be very different depending on what instance type and your config. Please open a new issue for your case with detailed reproducible steps, instance type and config of your job. I'm going to close this ticket due to inactivity from original poster. 

Some general information:
1. It's ok to see the following warning, it does not affect NCCL to communicate
```
NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol.
NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin symbol (v4 or v5).
```
2. If you are trying to use EFA, make sure the instance type supports it. 
3. For EFA supported instances, make sure you are running with a VPC with security group that's configured for EFA. Refer to the steps here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start-nccl-dlami.html
